### ISSUE TITLE
Why did you DELETE the event-dispatcher-message

### ISSUE THREAD

**Issue by alamin3000** [php-fig/event-dispatcher#20]
Can you tell me why the hell you had to DELETE the github repo all together??? You can provide message of deprecation and abandon... do you know what I had to go through when push an update to a site when composer CANNOT find package??  out of no where!!

Jack asses.

**Comment by Jean85** [comment]
I'm sorry if we caused any inconvenience, but that repository was just a test one that was used to flesh out PSR-14 while under development. That piece of code is no longer compatible with the approved version of the PSR, so it's unusable.

**Comment by Jean85** [comment]
And, I've locked this only because you resorted to insults.

We are all volunteers here, you were using our labor for free. Mind that next time.
