### ISSUE TITLE
after reading you can delete since you locked the other thread.

### ISSUE THREAD

**Issue by alamin3000** [php-fig/event-dispatcher#21]
Please don't use childish argument about FREE labor in 2019 about open source project.  this is simply two lines of code.  only reason we care so that we can bring php community to 'standard' even though we don't agree with the designs.

my only complain was that you can't delete a repo that was live in github and had some example blogs by zend guy referring to the repo. keeping repo up is free also.  just declare abandon just like all other repo and open source project does.  that was nothing but dumb thing to do.

**Comment by alamin3000** [comment]
'jack ass' maybe was bit much but 'dumb' certain is not.  anyway had a bad morning with this.  I am also writing a framework you can check phpcompose/compose for reference where I was using this repo to encapsulate events handling.  anyway.

**Comment by Jean85** [comment]
I can understand your frustration, but you cannot pretend anything from an OSS project. Yes, we could've mark the project as abandoned, our mistake, but this is not the way to address us, nor any OSS maintainer. We're devoting our free time to the improvement of the PHP ecosystem, we're not paid nor under any SLA.

I would have simply admitted the mistake if you didn't resort to insults.

**Comment by alamin3000** [comment]
sorry the insult came out of frustration early in the morning when can't push an update.  I knew the repo was not final but because I was wrapping with my own framework I thought I can always change when the psr gets finalized.  but never thought it would be delete from a PSR official GitHub 

anyway, I still can't use it because new interface uses 'object' type hint which is only available php 7.2... my server is running 7.1.

anyway. I apologized for the initial insult.

**Comment by Jean85** [comment]
Don't worry.

BTW the finalized PSR is ^7.2, so yeah, you're bound by that.

Ref #20. Closing.
